let data = [
  [
    "Romans",
    [
      [
        "boekExemplaar all twintigtot30",
        "../html/Subpagina's/ProductdetailpaginaVioleta.html",
        "Violeta",
        "../media/CoverVioleta_120x120.jpg",
        "Cover van het boek Violeta",
        "€ 25,50",
      ],
      [
        "boekExemplaar all tientot20",
        "../html/Subpagina's/ProductdetailpaginaProblemendieergeenzijn.html",
        "Problemen die er geen zijn",
        "../media/Herman-Brusselmans-Problemen-die-er-geen-zijn_120x120.jpg",
        "Cover van het boek Problemen die er geen zijn",
        "€ 18,50",
      ],
      [
        "boekExemplaar all tientot20",
        "../html/Subpagina's/ProductdetailpaginaColdenoughforsnow.html",
        "Cold Enough for Snow",
        "../media/jessica-au_cold-enough-for-snow-scaled_120x120.jpeg",
        "Cover van het boek Cold Enough for Snow",
        "€ 16,50",
      ],
      [
        "boekExemplaar all tientot20",
        "../html/Subpagina's/ProductdetailpaginaStranded.html",
        "Stranded",
        "../media/strandedCover_120x120.jpg",
        "Cover van boek Stranded",
        "€ 10,50",
      ],
      [
        "boekExemplaar all tientot20",
        "../html/Subpagina's/ProductdetailpaginaDesgenscommeeux.html",
        "Des gens comme eux",
        "../media/CoverDesgenscommeeux_120x120.jpg",
        "Cover van boek Des gens comme eux",
        "€ 12,50",
      ],
      [
        "boekExemplaar all dertigtot40",
        null,
        "anéantir",
        "../media/CoverAneantir_120x120.jpg",
        "Cover van het boek anéantir",
        "€ 33,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "Ein von Schatten begrenzter Raum",
        "../media/CoverEinvonSchatten_120x120.jpg",
        "Cover van het boek Ein von Schatten begrenzter Raum",
        "€ 24,50",
      ],
      [
        "boekExemplaar all tientot20",
        null,
        "Fieber 17",
        "../media/CoverFieber17_120x120.jpg",
        "Cover van het boek Fieber 17",
        "€ 18,50",
      ],
    ],
  ],
  [
    "Graphic novels",
    [
      [
        "boekExemplaar all twintigtot30",
        null,
        "De man van nu",
        "../media/CoverDemanVanNu_5_120x120.jpg",
        "Cover van de graphic novel De man van nu",
        "€ 24,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "Jheronimus",
        "../media/CoverJheronimus_120x120.jpg",
        "Cover van de graphic novel Jheronimus",
        "€ 25,50",
      ],
      [
        "boekExemplaar all dertigtot40",
        null,
        "In the Pines",
        "../media/CoverInthePines_120x120.jpg",
        "Cover van graphic novel In the Pines",
        "€ 30,50",
      ],
      [
        "boekExemplaar all dertigtot40",
        null,
        "Styx, of: De zesplankenkoorts",
        "../media/CoverStyx_120x120.jpg",
        "Cover van graphic novel Styx, of zesplankenkoorts",
        "€ 32,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "Rembrandt",
        "../media/CoverRembrandt_120x120.jpg",
        "Cover van graphic novel Rembrandt",
        "€ 20,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "Dansen op de vulkaan",
        "../media/CoverDansenopdevulkaan120x120.jpg",
        "",
        "€ 25,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "Door zonder familie",
        "../media/CoverDoorzonderfamilie_120x120.jpg",
        "Cover van graphic novel Door zonder familie",
        "€ 24,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "Het boek Genesis",
        "../media/CoverHetboekGenesis_120x120.jpg",
        "Cover van graphic novel Het boek van Genesis",
        "€ 22,50",
      ],
    ],
  ],
  [
    "Geschiedenisboeken",
    [
      [
        "boekExemplaar all twintigtot30",
        null,
        "Naar de sterren",
        "../media/CoverNaardesterren_120x120.jpg",
        "Cover van Boek Naar de sterren",
        "€ 23,50",
      ],
      [
        "boekExemplaar all dertigtot40",
        null,
        "Dit is Europa",
        "../media/CoverDitisEuropa_120x120.jpg",
        "Cover van Boek Dit is Europa",
        "€ 34,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "Het aanzien van 2021",
        "../media/CoverHetaanzienvan2021_120x120.jpg",
        "Cover van boek Het aanzien van 2021",
        "€ 21,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "Empire of Pain",
        "../media/CoverEmpires_of_Pain_120x120.jpg",
        "Cover van Boek Empire of Pain",
        "€ 23,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "Four Lost Cities: A Secret History of the Urban Age",
        "../media/CoverFourlostcities_120x120.jpg",
        "Cover van boek Four Lost Cities",
        "€ 20,50",
      ],
      [
        "boekExemplaar all twintigtot30",
        null,
        "L'Italie Depuis 1870",
        "../media/CoverItaliedepuis1870_120x120.jpg",
        "Cover van Boek L'Italie Depuis 1870",
        "€ 26,50",
      ],
      [
        "boekExemplaar all tientot20",
        null,
        "Les témoignages écrits de la Shoah",
        "../media/CoverLestemoignagesecrits_120x120.jpg",
        "Cover van boek Les témoignages écrits",
        "€ 13,50",
      ],
      [
        "boekExemplaar all tientot20",
        null,
        "Historia verdadera de la conquista de la Nueva España",
        "../media/CoverHistoria_verdadera_conquista_Nueva_Espana_portada_120x120.jpg",
        "Cover van boek Historia verdadera de la conquista de la Nueva España",
        "€ 19,50",
      ],
    ],
  ],
];